apiVersion: v1
entries:
  falkordb-browser:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2026-03-09T12:46:24.44004868Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 42cf96f550488b5964fa8f976d90790794770449f40a7152d6f4130c64d9a194
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.8.0.tgz
    version: 1.8.0
  - apiVersion: v2
    appVersion: 1.7.3
    created: "2026-03-09T12:46:24.43948086Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: b2c2cdfe0ac40b4be41c077836e1f5266244db6eddb33cf6a2e8d83c1d6a4174
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.3.tgz
    version: 1.7.3
  - apiVersion: v2
    appVersion: 1.7.2
    created: "2026-03-09T12:46:24.438919132Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 4a651fce827c0a1ffa0c25ced0af2e231fefaa6a3e2fa8d56e964fc82f48e684
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.2.tgz
    version: 1.7.2
  - apiVersion: v2
    appVersion: 1.7.1
    created: "2026-03-09T12:46:24.43835029Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 26067d9c13dfcd615cd79217f8af16d4e07c6637162a86c84c7befa577243941
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.1.tgz
    version: 1.7.1
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2026-03-09T12:46:24.437747375Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: b8658a2514760a9239c59dc7b8dec3094122ab39ce92a9beacb82f0befbd9c1c
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.0.tgz
    version: 1.7.0
  - apiVersion: v2
    appVersion: 1.6.7
    created: "2026-03-09T12:46:24.437121326Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 352f4d088992000dc621234b94bdd3326db9960e15832fe6d5ba0e364d9bbde9
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.6.7.tgz
    version: 1.6.7
generated: "2026-03-09T12:46:24.436271089Z"
