apiVersion: v1
entries:
  dm-sql-to-falkordb:
  - apiVersion: v2
    appVersion: 1.1.3
    created: "2026-06-24T06:47:22.859038008Z"
    description: Single control-plane multi-tool deployment for SQL-to-FalkorDB migration
      workloads.
    digest: d10e051c3c76780a0026d3d27f91e4439199a516652b2c1b3a5bee487d0b9691
    name: dm-sql-to-falkordb
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/dm-sql-to-falkordb-1.1.3.tgz
    version: 1.1.3
  - apiVersion: v2
    appVersion: 1.1.2
    created: "2026-06-24T06:47:22.858634888Z"
    description: Single control-plane multi-tool deployment for SQL-to-FalkorDB migration
      workloads.
    digest: 45734042dda3708200e1f03d414759ec5421616926af7bf68bb2b8a4434561f3
    name: dm-sql-to-falkordb
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/dm-sql-to-falkordb-1.1.2.tgz
    version: 1.1.2
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-06-24T06:47:22.858256013Z"
    description: Single control-plane multi-tool deployment for SQL-to-FalkorDB migration
      workloads.
    digest: 8394cd6b263364b8df307f872c74165824fa45b23a665fc5bc3a67670205527a
    name: dm-sql-to-falkordb
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/dm-sql-to-falkordb-0.1.0.tgz
    version: 0.1.0
  falkordb-browser:
  - apiVersion: v2
    appVersion: 2.0.10
    created: "2026-06-24T06:47:22.867660755Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 0c0646e7e80e39936ad68d60236ba29c3dbc242d1940a25ea22cee79dd57d3ef
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-2.0.10.tgz
    version: 2.0.10
  - apiVersion: v2
    appVersion: 2.0.9
    created: "2026-06-24T06:47:22.872943569Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 37d8bf6997d1b32040e47647e2575903ad250729ec6526bb498f0067eda863f1
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-2.0.9.tgz
    version: 2.0.9
  - apiVersion: v2
    appVersion: 2.0.8
    created: "2026-06-24T06:47:22.872377761Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 3e75cecfd347623e5f8cb745c2fa1f4c488fd79f971971a641b388bd7a6e06d3
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-2.0.8.tgz
    version: 2.0.8
  - apiVersion: v2
    appVersion: 2.0.7
    created: "2026-06-24T06:47:22.871857619Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 9ec090df153165d71dbff471aaa6f81cefbe3e9f7339623a36e0ece103840a09
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-2.0.7.tgz
    version: 2.0.7
  - apiVersion: v2
    appVersion: 2.0.6
    created: "2026-06-24T06:47:22.871321057Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: c12b911053419d639b3e6d6b2b28d3e5ddd83c63c37f2f18f74e07ffd7a41fe1
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-2.0.6.tgz
    version: 2.0.6
  - apiVersion: v2
    appVersion: 2.0.5
    created: "2026-06-24T06:47:22.870770448Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: ca23035be35091f39b7a2c439140072423b41df4d21f4eb189a2a799854a55b8
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-2.0.5.tgz
    version: 2.0.5
  - apiVersion: v2
    appVersion: 2.0.4
    created: "2026-06-24T06:47:22.870239496Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 025e013209083a4a0a5814e8bc9ffd634c8cef791b21f5be3fedb747262f3621
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-2.0.4.tgz
    version: 2.0.4
  - apiVersion: v2
    appVersion: 2.0.3
    created: "2026-06-24T06:47:22.869632741Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 5072cb5ac43dd8f16112a95135caa70049ad73201cd4ed68dc641b1ca52edf74
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-2.0.3.tgz
    version: 2.0.3
  - apiVersion: v2
    appVersion: 2.0.2
    created: "2026-06-24T06:47:22.868222976Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 6663dbade3115da04843843a6de2ef616982a514d6b59912e68708b6ead0b59e
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-2.0.2.tgz
    version: 2.0.2
  - apiVersion: v2
    appVersion: 2.0.1
    created: "2026-06-24T06:47:22.867095168Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 69f8e50d1ee1e45a7b79e17423799f640f80c92cf1dea894245debcedf644b58
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-2.0.1.tgz
    version: 2.0.1
  - apiVersion: v2
    appVersion: 1.9.4
    created: "2026-06-24T06:47:22.86655059Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 72bc3d654902d2c692893ec1ce567a68a41d98d495e44aa0c72232d11f1b4780
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.9.4.tgz
    version: 1.9.4
  - apiVersion: v2
    appVersion: 1.9.3
    created: "2026-06-24T06:47:22.866017664Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: d4a2ef4423d89327aca707f0c9486daf9fbdda06d33a3e8626f441b508eca466
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.9.3.tgz
    version: 1.9.3
  - apiVersion: v2
    appVersion: 1.9.2
    created: "2026-06-24T06:47:22.865457157Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 5cf5f09bbdc53995b85ce7af71cf700ae94e91386995b8a78b879de73f7ab122
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.9.2.tgz
    version: 1.9.2
  - apiVersion: v2
    appVersion: 1.9.1
    created: "2026-06-24T06:47:22.864856373Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 1065c769ae2ce7c6a5d727aa4335214308d4a38a72dea2b6b239bc3dea69bf9a
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.9.1.tgz
    version: 1.9.1
  - apiVersion: v2
    appVersion: 1.9.0
    created: "2026-06-24T06:47:22.864311886Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 83e403d86a57b0a3407a17a6b679108936927212fa9d7e69fac1562f37011a33
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.9.0.tgz
    version: 1.9.0
  - apiVersion: v2
    appVersion: 1.8.1
    created: "2026-06-24T06:47:22.863745757Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 6883a2d224d77571dd3d7676891bdec48c5fd15234d1515e7cf24b634a34a47d
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.8.1.tgz
    version: 1.8.1
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2026-06-24T06:47:22.863214265Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 42cf96f550488b5964fa8f976d90790794770449f40a7152d6f4130c64d9a194
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.8.0.tgz
    version: 1.8.0
  - apiVersion: v2
    appVersion: 1.7.3
    created: "2026-06-24T06:47:22.862627247Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: b2c2cdfe0ac40b4be41c077836e1f5266244db6eddb33cf6a2e8d83c1d6a4174
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.3.tgz
    version: 1.7.3
  - apiVersion: v2
    appVersion: 1.7.2
    created: "2026-06-24T06:47:22.861347135Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 4a651fce827c0a1ffa0c25ced0af2e231fefaa6a3e2fa8d56e964fc82f48e684
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.2.tgz
    version: 1.7.2
  - apiVersion: v2
    appVersion: 1.7.1
    created: "2026-06-24T06:47:22.860765488Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 26067d9c13dfcd615cd79217f8af16d4e07c6637162a86c84c7befa577243941
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.1.tgz
    version: 1.7.1
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2026-06-24T06:47:22.86022072Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: b8658a2514760a9239c59dc7b8dec3094122ab39ce92a9beacb82f0befbd9c1c
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.7.0.tgz
    version: 1.7.0
  - apiVersion: v2
    appVersion: 1.6.7
    created: "2026-06-24T06:47:22.85963245Z"
    description: A Helm chart for deploying FalkorDB Browser to Kubernetes
    digest: 012dbb94ea851effd870584f0267c5155ea0a298d969a74415b863865a3dd907
    home: https://github.com/FalkorDB/falkordb-browser
    keywords:
    - falkordb
    - browser
    - graph
    - database
    maintainers:
    - name: FalkorDB
      url: https://www.falkordb.com
    name: falkordb-browser
    sources:
    - https://github.com/FalkorDB/falkordb-browser
    type: application
    urls:
    - https://falkordb.github.io/helm-charts/falkordb-browser-1.6.7.tgz
    version: 1.6.7
generated: "2026-06-24T06:47:22.857695275Z"
